//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/PlayerInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Battle"",
            ""id"": ""ea1e08e4-f06a-4b5b-8fba-2cd7f1faf345"",
            ""actions"": [
                {
                    ""name"": ""PuzzleDrawUp"",
                    ""type"": ""Button"",
                    ""id"": ""74bf350c-a8e9-4af0-a088-df902d22ff3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleDrawDown"",
                    ""type"": ""Button"",
                    ""id"": ""9220e6de-9f88-4ebe-807e-3fc3b206786e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleDrawLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f44d6d36-f2bf-43d2-a284-2735ce56938a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleDrawRight"",
                    ""type"": ""Button"",
                    ""id"": ""1c79727a-407a-43c3-8a3c-db7367fe723b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleSelectL"",
                    ""type"": ""Button"",
                    ""id"": ""ddb92ea4-9b8b-49b7-bbbb-a15c260fb2ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleSelectR"",
                    ""type"": ""Button"",
                    ""id"": ""6dc60760-0141-4933-865e-6d9b7671b148"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzlePageL"",
                    ""type"": ""Button"",
                    ""id"": ""99ac964f-753e-41d6-96da-735a8ada9e1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzlePageR"",
                    ""type"": ""Button"",
                    ""id"": ""58c08138-b83a-49d1-9b25-e53975ac37af"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleReset"",
                    ""type"": ""Button"",
                    ""id"": ""e702cb36-77bc-4b7a-a4f4-b108c3d66e3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99614bca-84cb-46a0-a9c0-583cd3379ccf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleDrawUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4fdf58b-8608-4932-8d9f-fa2ad020530d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleDrawDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d816642d-d400-4d72-b6b7-aa744690df52"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleDrawLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c710e68-984c-40c0-8cd8-aa3affdbd182"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleDrawRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f60a6aae-c67c-4382-81c2-bf53dfce2e8a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleSelectL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""591eef8b-3f60-4355-aa22-3d0a23994f4a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleSelectR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf38415-c769-400d-b9a7-039218b52fc0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzlePageL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49f2fc93-5cc2-4d91-9747-c3cca3924c36"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzlePageR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""155b02d2-183f-46d7-9e42-b6e60fc1716b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleReset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Battle
        m_Battle = asset.FindActionMap("Battle", throwIfNotFound: true);
        m_Battle_PuzzleDrawUp = m_Battle.FindAction("PuzzleDrawUp", throwIfNotFound: true);
        m_Battle_PuzzleDrawDown = m_Battle.FindAction("PuzzleDrawDown", throwIfNotFound: true);
        m_Battle_PuzzleDrawLeft = m_Battle.FindAction("PuzzleDrawLeft", throwIfNotFound: true);
        m_Battle_PuzzleDrawRight = m_Battle.FindAction("PuzzleDrawRight", throwIfNotFound: true);
        m_Battle_PuzzleSelectL = m_Battle.FindAction("PuzzleSelectL", throwIfNotFound: true);
        m_Battle_PuzzleSelectR = m_Battle.FindAction("PuzzleSelectR", throwIfNotFound: true);
        m_Battle_PuzzlePageL = m_Battle.FindAction("PuzzlePageL", throwIfNotFound: true);
        m_Battle_PuzzlePageR = m_Battle.FindAction("PuzzlePageR", throwIfNotFound: true);
        m_Battle_PuzzleReset = m_Battle.FindAction("PuzzleReset", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Battle.enabled, "This will cause a leak and performance issues, PlayerInput.Battle.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Battle
    private readonly InputActionMap m_Battle;
    private List<IBattleActions> m_BattleActionsCallbackInterfaces = new List<IBattleActions>();
    private readonly InputAction m_Battle_PuzzleDrawUp;
    private readonly InputAction m_Battle_PuzzleDrawDown;
    private readonly InputAction m_Battle_PuzzleDrawLeft;
    private readonly InputAction m_Battle_PuzzleDrawRight;
    private readonly InputAction m_Battle_PuzzleSelectL;
    private readonly InputAction m_Battle_PuzzleSelectR;
    private readonly InputAction m_Battle_PuzzlePageL;
    private readonly InputAction m_Battle_PuzzlePageR;
    private readonly InputAction m_Battle_PuzzleReset;
    /// <summary>
    /// Provides access to input actions defined in input action map "Battle".
    /// </summary>
    public struct BattleActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BattleActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleDrawUp".
        /// </summary>
        public InputAction @PuzzleDrawUp => m_Wrapper.m_Battle_PuzzleDrawUp;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleDrawDown".
        /// </summary>
        public InputAction @PuzzleDrawDown => m_Wrapper.m_Battle_PuzzleDrawDown;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleDrawLeft".
        /// </summary>
        public InputAction @PuzzleDrawLeft => m_Wrapper.m_Battle_PuzzleDrawLeft;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleDrawRight".
        /// </summary>
        public InputAction @PuzzleDrawRight => m_Wrapper.m_Battle_PuzzleDrawRight;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleSelectL".
        /// </summary>
        public InputAction @PuzzleSelectL => m_Wrapper.m_Battle_PuzzleSelectL;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleSelectR".
        /// </summary>
        public InputAction @PuzzleSelectR => m_Wrapper.m_Battle_PuzzleSelectR;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzlePageL".
        /// </summary>
        public InputAction @PuzzlePageL => m_Wrapper.m_Battle_PuzzlePageL;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzlePageR".
        /// </summary>
        public InputAction @PuzzlePageR => m_Wrapper.m_Battle_PuzzlePageR;
        /// <summary>
        /// Provides access to the underlying input action "Battle/PuzzleReset".
        /// </summary>
        public InputAction @PuzzleReset => m_Wrapper.m_Battle_PuzzleReset;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Battle; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BattleActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BattleActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BattleActions" />
        public void AddCallbacks(IBattleActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleActionsCallbackInterfaces.Add(instance);
            @PuzzleDrawUp.started += instance.OnPuzzleDrawUp;
            @PuzzleDrawUp.performed += instance.OnPuzzleDrawUp;
            @PuzzleDrawUp.canceled += instance.OnPuzzleDrawUp;
            @PuzzleDrawDown.started += instance.OnPuzzleDrawDown;
            @PuzzleDrawDown.performed += instance.OnPuzzleDrawDown;
            @PuzzleDrawDown.canceled += instance.OnPuzzleDrawDown;
            @PuzzleDrawLeft.started += instance.OnPuzzleDrawLeft;
            @PuzzleDrawLeft.performed += instance.OnPuzzleDrawLeft;
            @PuzzleDrawLeft.canceled += instance.OnPuzzleDrawLeft;
            @PuzzleDrawRight.started += instance.OnPuzzleDrawRight;
            @PuzzleDrawRight.performed += instance.OnPuzzleDrawRight;
            @PuzzleDrawRight.canceled += instance.OnPuzzleDrawRight;
            @PuzzleSelectL.started += instance.OnPuzzleSelectL;
            @PuzzleSelectL.performed += instance.OnPuzzleSelectL;
            @PuzzleSelectL.canceled += instance.OnPuzzleSelectL;
            @PuzzleSelectR.started += instance.OnPuzzleSelectR;
            @PuzzleSelectR.performed += instance.OnPuzzleSelectR;
            @PuzzleSelectR.canceled += instance.OnPuzzleSelectR;
            @PuzzlePageL.started += instance.OnPuzzlePageL;
            @PuzzlePageL.performed += instance.OnPuzzlePageL;
            @PuzzlePageL.canceled += instance.OnPuzzlePageL;
            @PuzzlePageR.started += instance.OnPuzzlePageR;
            @PuzzlePageR.performed += instance.OnPuzzlePageR;
            @PuzzlePageR.canceled += instance.OnPuzzlePageR;
            @PuzzleReset.started += instance.OnPuzzleReset;
            @PuzzleReset.performed += instance.OnPuzzleReset;
            @PuzzleReset.canceled += instance.OnPuzzleReset;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BattleActions" />
        private void UnregisterCallbacks(IBattleActions instance)
        {
            @PuzzleDrawUp.started -= instance.OnPuzzleDrawUp;
            @PuzzleDrawUp.performed -= instance.OnPuzzleDrawUp;
            @PuzzleDrawUp.canceled -= instance.OnPuzzleDrawUp;
            @PuzzleDrawDown.started -= instance.OnPuzzleDrawDown;
            @PuzzleDrawDown.performed -= instance.OnPuzzleDrawDown;
            @PuzzleDrawDown.canceled -= instance.OnPuzzleDrawDown;
            @PuzzleDrawLeft.started -= instance.OnPuzzleDrawLeft;
            @PuzzleDrawLeft.performed -= instance.OnPuzzleDrawLeft;
            @PuzzleDrawLeft.canceled -= instance.OnPuzzleDrawLeft;
            @PuzzleDrawRight.started -= instance.OnPuzzleDrawRight;
            @PuzzleDrawRight.performed -= instance.OnPuzzleDrawRight;
            @PuzzleDrawRight.canceled -= instance.OnPuzzleDrawRight;
            @PuzzleSelectL.started -= instance.OnPuzzleSelectL;
            @PuzzleSelectL.performed -= instance.OnPuzzleSelectL;
            @PuzzleSelectL.canceled -= instance.OnPuzzleSelectL;
            @PuzzleSelectR.started -= instance.OnPuzzleSelectR;
            @PuzzleSelectR.performed -= instance.OnPuzzleSelectR;
            @PuzzleSelectR.canceled -= instance.OnPuzzleSelectR;
            @PuzzlePageL.started -= instance.OnPuzzlePageL;
            @PuzzlePageL.performed -= instance.OnPuzzlePageL;
            @PuzzlePageL.canceled -= instance.OnPuzzlePageL;
            @PuzzlePageR.started -= instance.OnPuzzlePageR;
            @PuzzlePageR.performed -= instance.OnPuzzlePageR;
            @PuzzlePageR.canceled -= instance.OnPuzzlePageR;
            @PuzzleReset.started -= instance.OnPuzzleReset;
            @PuzzleReset.performed -= instance.OnPuzzleReset;
            @PuzzleReset.canceled -= instance.OnPuzzleReset;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BattleActions.UnregisterCallbacks(IBattleActions)" />.
        /// </summary>
        /// <seealso cref="BattleActions.UnregisterCallbacks(IBattleActions)" />
        public void RemoveCallbacks(IBattleActions instance)
        {
            if (m_Wrapper.m_BattleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BattleActions.AddCallbacks(IBattleActions)" />
        /// <seealso cref="BattleActions.RemoveCallbacks(IBattleActions)" />
        /// <seealso cref="BattleActions.UnregisterCallbacks(IBattleActions)" />
        public void SetCallbacks(IBattleActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BattleActions" /> instance referencing this action map.
    /// </summary>
    public BattleActions @Battle => new BattleActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Battle" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BattleActions.AddCallbacks(IBattleActions)" />
    /// <seealso cref="BattleActions.RemoveCallbacks(IBattleActions)" />
    public interface IBattleActions
    {
        /// <summary>
        /// Method invoked when associated input action "PuzzleDrawUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleDrawUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleDrawDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleDrawDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleDrawLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleDrawLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleDrawRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleDrawRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleSelectL" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleSelectL(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleSelectR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleSelectR(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzlePageL" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzlePageL(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzlePageR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzlePageR(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PuzzleReset" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPuzzleReset(InputAction.CallbackContext context);
    }
}
